export type MassTemplateType = {
  name: string;
  type: string;
  m: number;
  radius: number;
  tilt: number;
  atmosphere?: string;
  temperature?: number;
  nonStellarProceduralManifestation?: boolean;
};

export type MassTemplateCategoryType = {
  name: string;
  templates: MassTemplateType[];
};

const massTemplates: MassTemplateCategoryType[] = [
  {
    name: "Stars",
    templates: [
      {
        name: "Sun",
        type: "star",
        m: 1,
        radius: 10270,
        tilt: 0,
        temperature: 5778,
      },
    ],
  },
  {
    name: "Planets",
    templates: [
      {
        name: "Mercury",
        type: "terrestial planet",
        m: 1.652e-7,
        radius: 36.101083032490976,
        tilt: -0.03,
      },
      {
        name: "Venus",
        type: "terrestial planet",
        m: 2.447e-6,
        radius: 86.95652173913044,
        tilt: 2.63,
        atmosphere: "beige",
      },
      {
        name: "Earth",
        type: "terrestial planet",
        m: 3.003e-6,
        radius: 91.74311926605505,
        tilt: -23.44,
        atmosphere: "skyblue",
      },
      {
        name: "Mars",
        type: "terrestial planet",
        m: 3.213e-7,
        radius: 48.62385321100918,
        tilt: 25.19,
        atmosphere: "orange",
      },
      {
        name: "Jupiter",
        type: "gas giant planet",
        m: 0.0009543,
        radius: 1027.5229357798166,
        tilt: -3.13,
        atmosphere: "beige",
      },
      {
        name: "Saturn",
        type: "gas giant planet",
        m: 0.0002857,
        radius: 862.3853211009175,
        tilt: -26.73,
        atmosphere: "beige",
      },
      {
        name: "Uranus",
        type: "ice giant planet",
        m: 4.366e-5,
        radius: 377.5,
        tilt: -97.77,
        atmosphere: "lightcyan",
      },
      {
        name: "Neptune",
        type: "ice giant planet",
        m: 5.151e-5,
        radius: 363.5,
        tilt: -28.32,
        atmosphere: "lightskyblue",
      },
    ],
  },
  {
    name: "Moons",
    templates: [
      {
        name: "Moon",
        type: "moon",
        m: 3.69396868e-8,
        radius: 22.93577981651376,
        tilt: -1.54,
      },
      {
        name: "Phobos",
        type: "moon",
        m: 5.359189909029e-15,
        radius: 1,
        tilt: 0,
      },
      {
        name: "Deimos",
        type: "moon",
        m: 5.359189909029e-15,
        radius: 1,
        tilt: 0,
      },
      {
        name: "Io",
        type: "moon",
        m: 4.490848296995278e-8,
        radius: 24.082568807339452,
        tilt: -3.13,
      },
      {
        name: "Europa",
        type: "moon",
        m: 2.413291634272764e-8,
        radius: 22.477064220183486,
        tilt: -3.13,
      },
      {
        name: "Ganymede",
        type: "moon",
        m: 7.450777301989e-8,
        radius: 34.633027522935784,
        tilt: -3.13,
      },
      {
        name: "Callisto",
        type: "moon",
        m: 5.4300826548e-8,
        radius: 35.74007220216607,
        tilt: -3.13,
      },
      {
        name: "Triton",
        type: "moon",
        m: 1.0764e-8,
        radius: 19.97,
        tilt: -28.32,
      },
      {
        name: "Charon",
        type: "moon",
        m: 7.979e-10,
        radius: 8.95,
        tilt: 119.61,
      },
    ],
  },
  {
    name: "Dwarf Planets",
    templates: [
      {
        name: "Ceres",
        type: "dwarf planet",
        m: 4.722e-10,
        radius: 6.86,
        tilt: 4.0,
      },
      {
        name: "Pluto",
        type: "dwarf planet",
        m: 6.551e-9,
        radius: 17.55,
        tilt: 119.61,
      },
      {
        name: "Eris",
        type: "dwarf planet",
        m: 8.278e-9,
        radius: 16.76,
        tilt: 78.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Haumea",
        type: "dwarf planet",
        m: 2.014e-9,
        radius: 11.24,
        tilt: 126.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Makemake",
        type: "dwarf planet",
        m: 1.559e-9,
        radius: 10.3,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Gonggong",
        type: "dwarf planet",
        m: 8.797e-10,
        radius: 8.86,
        tilt: 106.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Quaoar",
        type: "dwarf planet",
        m: 6.034e-10,
        radius: 7.99,
        tilt: 14.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Sedna",
        type: "dwarf planet",
        m: 5.028e-10,
        radius: 7.17,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Orcus",
        type: "dwarf planet",
        m: 3.178e-10,
        radius: 6.6,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
    ],
  },
  {
    name: "Asteroids & Comets",
    templates: [
      {
        name: "Ceres",
        type: "dwarf planet",
        m: 4.722e-10,
        radius: 6.86,
        tilt: 4.0,
      },
      {
        name: "Pluto",
        type: "dwarf planet",
        m: 6.551e-9,
        radius: 17.55,
        tilt: 119.61,
      },
      {
        name: "Vesta",
        type: "asteroid",
        m: 1.302e-10,
        radius: 3.81,
        tilt: 29.1,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Pallas",
        type: "asteroid",
        m: 1.026e-10,
        radius: 3.7,
        tilt: 84.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Hygiea",
        type: "asteroid",
        m: 4.359e-11,
        radius: 3.15,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Interamnia",
        type: "asteroid",
        m: 1.91e-11,
        radius: 2.36,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Juno",
        type: "asteroid",
        m: 1.343e-11,
        radius: 1.79,
        tilt: 51.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Psyche",
        type: "asteroid",
        m: 1.212e-11,
        radius: 1.64,
        tilt: 95.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Ida",
        type: "asteroid",
        m: 1.181e-14,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Eros",
        type: "asteroid",
        m: 3.362e-15,
        radius: 1.2,
        tilt: 89.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Bennu",
        type: "asteroid",
        m: 3.685e-20,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Ryugu",
        type: "asteroid",
        m: 2.263e-19,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Itokawa",
        type: "asteroid",
        m: 1.764e-20,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Halley",
        type: "comet",
        m: 1.106e-16,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "67P/Churyumov-Gerasimenko",
        type: "comet",
        m: 5.019e-18,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Hale-Bopp",
        type: "comet",
        m: 6.536e-15,
        radius: 1.2,
        tilt: 0.0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Borisov",
        type: "comet",
        m: 1.005570862e-45,
        radius: 1.2,
        tilt: 0,
        nonStellarProceduralManifestation: true,
      },
      {
        name: "Generic Asteroid",
        type: "asteroid",
        m: 1.005570862e-45,
        radius: 1.2,
        tilt: 0,
        nonStellarProceduralManifestation: true,
      },
    ],
  },
];

export default massTemplates;
